[package]
name = "rote"
version = "0.1.0"
authors = ["suede"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.7.1"
dirs = "2.0.2"
chrono = "0.4"
